### ISSUE TITLE
Regenerate or replace tui-designer (broken against current TG; excluded from the package in #23)

### ISSUE THREAD

**Issue by tig** [tui-cs/Terminal.Gui.templates#24]
`tui-designer`'s generated `MyView.Designer.cs` no longer compiles against current Terminal.Gui — it references `Terminal.Gui.ViewBase.ShadowStyle`, which was **renamed to `ShadowStyles`** and **moved from `View` onto the `Margin` adornment**:

```
MyView.Designer.cs(41,32): error CS0234: 'ShadowStyle' does not exist in 'Terminal.Gui.ViewBase'
```

It was build-frozen at `2.0.0-alpha.4309` and never CI-build-tested, so the drift went unnoticed. In #23 it is **excluded from the package and CI** so the relaunch doesn't ship a broken template.

The generated `.Designer.cs` is a TerminalGuiDesigner **tool** snapshot — hand-patching it is fragile and re-drifts every TG release, and an AI agent can't drive the GUI designer to regenerate it. Options:

- [ ] **Regenerate** `MyView.Designer.cs` with the current TerminalGuiDesigner against current TG, then add it to the CI build-test + the package.
- [ ] **Replace** the designer template with a hand-coded, agent-friendly multi-view example (menu + status bar + a couple of views), with its own `AGENTS.md` — more useful for agents than a designer-tool snapshot.
- [ ] **Drop** `tui-designer` if the designer workflow isn't a priority for the agent-first relaunch.

Part of the relaunch tracked in #22.

**Comment by tig** [comment]
Deprioritizing: TerminalGuiDesigner for v2 isn't released yet, so a v2 `tui-designer` template is moot for now. Leaving this open as the tracking item; Phase-2 effort is going into a flagship multi-view `tui` template instead (more useful for AI agents than a designer-tool snapshot).
